---
- name: uninstall system ruby
  apt: name=ruby state=absent
  sudo: yes

- name: download chruby package
  get_url:
    url=https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz
    dest="{{ ansible_env.HOME }}/chruby-0.3.9.tar.gz" 
  
- name: unpack chruby package
  unarchive:
    src={{ ansible_env.HOME }}/chruby-0.3.9.tar.gz
    dest={{ ansible_env.HOME }}
    copy=no
    creates="{{ ansible_env.HOME }}/chruby-0.3.9"

- name: setup chruby
  shell: scripts/setup.sh
  args:
    chdir: "{{ ansible_env.HOME }}/chruby-0.3.9"
    creates: /usr/local/share/chruby/chruby.sh
  sudo: yes

- name: download ruby-install
  get_url:
    url=https://github.com/postmodern/ruby-install/archive/v0.5.0.tar.gz
    dest="{{ ansible_env.HOME }}/ruby-install-0.5.0.tar.gz"
  
- name: unpack ruby-install
  unarchive:
    src={{ ansible_env.HOME }}/ruby-install-0.5.0.tar.gz
    dest={{ ansible_env.HOME }}
    copy=no
    creates="{{ ansible_env.HOME }}/ruby-install-0.5.0"

- name: install ruby-install
  shell: make install
  args:
    chdir: "{{ ansible_env.HOME }}/ruby-install-0.5.0"
  sudo: yes

- name: detect ruby version
  shell: bash -lc "ruby -v | grep 2.2.0"
  register: required_ruby_version_installed
  ignore_errors: yes

- name: install ruby
  shell: ruby-install --rubies-dir /opt/rubies ruby 2.2.0
  when: required_ruby_version_installed|failed
  sudo: yes

- name: install bundler
  shell: bash -lc "gem install bundler"

  # to do:
  # create /etc/profile.d to set system ruby version (chruby 2.0.0)
  # cleanup, organization, etc.
